"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {createEnquiry,type Enquiry} from "@/lib/firebase/data";
const phone="71638995";const whatsapp="26771638995";
type Draft={name:string;phone:string;problem:string;location:string;notes:string};
export default function OrderForm(){
 const[saved,setSaved]=useState<Draft>({name:"",phone:"",problem:"",location:"",notes:""});const[submitted,setSubmitted]=useState(false),[reference,setReference]=useState(""),[pendingSync,setPendingSync]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem("exquisite-enquiry-draft");if(raw)setSaved(prev=>({...prev,...JSON.parse(raw)}))}catch{}},[]);
 function remember(next:Draft){setSaved(next);try{localStorage.setItem("exquisite-enquiry-draft",JSON.stringify(next))}catch{}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");const form=new FormData(event.currentTarget);const name=String(form.get("name")??"").trim(),customerPhone=String(form.get("phone")??"").trim(),problem=String(form.get("problem")??"").trim(),location=String(form.get("location")??"").trim(),notes=String(form.get("notes")??"").trim(),preferredContact=String(form.get("preferredContact")??"whatsapp") as Enquiry["preferredContact"];if(!name||!customerPhone||!problem){setError("Please add your name, phone / WhatsApp number and what needs attention.");setBusy(false);return}const payload:Omit<Enquiry,"id">={createdAt:new Date().toISOString(),name,phone:customerPhone,problem,preferredContact,location,notes,status:"New"};try{const{id,writePromise}=createEnquiry(payload);setReference(id);if(!navigator.onLine){void writePromise.catch(()=>{});setPendingSync(true)}else{await writePromise;setPendingSync(false)}remember({name,phone:customerPhone,problem,location,notes});setSubmitted(true);event.currentTarget.reset()}catch(err){console.error(err);setError("We could not save the enquiry online. Check the connection and try again, or WhatsApp 71638995.")}finally{setBusy(false)}}
 if(submitted)return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="brand"><span className="brandMark">E</span><span>EXQUISITE</span></Link><a className="button buttonLight" href={"https://wa.me/"+whatsapp}>WhatsApp</a></div><section className="orderCard confirm"><div className="confirmIcon">{pendingSync?"↻":"✓"}</div><span className="kicker">{pendingSync?"Saved on this phone":"Enquiry saved"}</span><h1>{pendingSync?"Waiting to sync.":"We have your enquiry."}</h1><p>{pendingSync?"Your enquiry is stored locally and has not yet reached Exquisite. Reconnect this device so Firestore can synchronize it.":"Your enquiry was written to the Exquisite enquiry queue. Exquisite can now follow up using the details you provided."}</p><strong>Reference #{reference.slice(0,8).toUpperCase()}</strong><div className="actions centered"><Link className="button buttonPrimary" href={"/orders/"+reference}>View status</Link><a className="button buttonLight" href={"https://wa.me/"+whatsapp}>WhatsApp 71638995</a><Link className="button buttonLight" href="/">Back home</Link></div></section></div></main>;
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="brand"><span className="brandMark">E</span><span>EXQUISITE</span></Link><a className="button buttonLight" href={"tel:"+phone}>71638995</a></div><div className="sectionHead"><div><span className="kicker">Free Damage Analysis</span><h1>Tell us what needs attention.</h1><p>Leave the details below. No account is required.</p></div></div><form className="orderCard enquiryForm" onSubmit={submit}><div className="fieldGrid"><label>Name<input name="name" value={saved.name} onChange={e=>remember({...saved,name:e.target.value})} autoComplete="name" required/></label><label>Phone / WhatsApp<input name="phone" value={saved.phone} onChange={e=>remember({...saved,phone:e.target.value})} autoComplete="tel" required/></label><label className="fieldFull">What needs attention?<textarea name="problem" value={saved.problem} onChange={e=>remember({...saved,problem:e.target.value})} placeholder="Roof leak, damp wall, waterproofing problem…" required/></label><label>Location / landmark <span>(optional)</span><input name="location" value={saved.location} onChange={e=>remember({...saved,location:e.target.value})}/></label><label>Preferred contact<select name="preferredContact" defaultValue="whatsapp"><option value="whatsapp">WhatsApp</option><option value="phone">Phone call</option></select></label><label className="fieldFull">Anything else? <span>(optional)</span><textarea name="notes" value={saved.notes} onChange={e=>remember({...saved,notes:e.target.value})} placeholder="Useful details about the damage or access…"/></label></div>{error&&<p role="alert" className="notice">{error}</p>}<div className="formFooter"><p className="orderTruth">Free Damage Analysis is supplied by Exquisite. Exact prices and payment arrangements are confirmed directly with the business.</p><button className="button buttonPrimary" type="submit" disabled={busy}>{busy?"Saving enquiry…":"Request damage analysis"}</button></div></form></div></main>
}