"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getBusinessSettings,type BusinessSettings} from "@/lib/firebase/data";
const phone="71638995"; const whatsapp="26771638995";
export default function Home(){
 const[settings,setSettings]=useState<BusinessSettings|null>(null);
 useEffect(()=>{void getBusinessSettings().then(setSettings).catch(()=>setSettings(null))},[]);
 const serviceText=settings?.serviceText||"For all your roofing and wall waterproofing";
 return <main className="exquisiteSite">
  <div className="noticeBar"><div className="container noticeInner"><strong>EXQUISITE WATERPROOF SERVICES</strong><span>71638995</span></div></div>
  <nav className="nav"><div className="container navInner"><Link href="/" className="brand"><span className="brandMark">E</span><span>EXQUISITE</span></Link><div className="navLinks"><a href="#services">Services</a><a href="#damage">Damage analysis</a><a href="#contact">Contact</a></div><a className="button buttonPrimary" href={"https://wa.me/"+whatsapp}>WhatsApp us</a></div></nav>
  <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">EXQUISITE WATERPROOF SERVICES</span><h1>Keep the<br/><em>water out.</em></h1><p className="lead">{serviceText}.</p><div className="actions"><Link className="button buttonPrimary" href="/order">Request help</Link><a className="button buttonLight" href={"tel:"+phone}>Call 71638995</a></div><div className="promiseRow"><div><strong>FREE</strong><span>Damage Analysis</span></div><div><strong>FLEXIBLE</strong><span>Payment Terms</span></div></div></div><div className="roofVisual" aria-label="Roof and wall waterproofing"><div className="roofShape"><span>ROOF</span><span>WALL</span><span>PROTECTION</span></div><div className="waterLine"></div></div></div></section>
  <section id="services" className="section"><div className="container"><div className="sectionHead"><div><span className="kicker">What needs fixing?</span><h2>Roofing & wall waterproofing</h2></div><span className="sectionTag">Botswana</span></div><div className="serviceGrid"><article><span className="serviceIcon">01</span><h3>ROOF</h3><p>Tell us where water is getting in or where you need waterproofing attention.</p></article><article><span className="serviceIcon">02</span><h3>WALL</h3><p>Describe damp, leaking or water-related wall problems for the assessment.</p></article><article><span className="serviceIcon">03</span><h3>ANALYSIS</h3><p>Request the supplied free damage analysis and let Exquisite follow up with you.</p></article></div></div></section>
  <section id="damage" className="damageSection"><div className="container damageGrid"><div><span className="kicker">Start with the problem</span><h2>Free Damage Analysis</h2><p>Use the enquiry form to tell Exquisite what is happening. If you are offline, the installed app can keep an eligible enquiry locally until connectivity returns.</p><div className="actions"><Link className="button buttonPrimary" href="/order">Start an enquiry</Link><a className="button buttonLight" href={"https://wa.me/"+whatsapp}>WhatsApp 71638995</a></div></div><div className="damageCard"><strong>FLEXIBLE PAYMENT TERMS</strong><p>Payment terms are supplied as flexible. Any exact price or payment arrangement should be confirmed directly with Exquisite.</p></div></div></section>
  <section id="contact" className="section contactSection"><div className="container contactGrid"><div><span className="kicker">Talk to Exquisite</span><h2>Tell us what is wrong.</h2><p>Call or WhatsApp <strong>71638995</strong>. You can also leave an enquiry through the app.</p></div><div className="contactCard"><strong>71638995</strong><span>Exquisite Waterproof Services</span><div className="actions"><a className="button buttonPrimary" href={"tel:"+phone}>Call</a><a className="button buttonLight" href={"https://wa.me/"+whatsapp}>WhatsApp</a><Link className="button buttonLight" href="/order">Enquiry</Link></div></div></div></section>
  <footer className="footer"><div className="container footerInner"><div><strong>EXQUISITE WATERPROOF SERVICES</strong><span>For all your roofing and wall waterproofing</span></div><Link href="/order" className="button buttonPrimary">Request help</Link></div></footer>
 </main>
}